// Generated by Dagger (https://dagger.dev).
package com.gksoftwaresolutions.catapp.view.home;

import com.gksoftwaresolutions.catapp.viewModel.HomeViewModel;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class HomeFragment_MembersInjector implements MembersInjector<HomeFragment> {
  private final Provider<HomeViewModel> mViewModelProvider;

  public HomeFragment_MembersInjector(Provider<HomeViewModel> mViewModelProvider) {
    this.mViewModelProvider = mViewModelProvider;
  }

  public static MembersInjector<HomeFragment> create(Provider<HomeViewModel> mViewModelProvider) {
    return new HomeFragment_MembersInjector(mViewModelProvider);
  }

  @Override
  public void injectMembers(HomeFragment instance) {
    injectMViewModel(instance, mViewModelProvider.get());
  }

  @InjectedFieldSignature("com.gksoftwaresolutions.catapp.view.home.HomeFragment.mViewModel")
  public static void injectMViewModel(HomeFragment instance, HomeViewModel mViewModel) {
    instance.mViewModel = mViewModel;
  }
}
